// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'background': string;
  'button': string;
  'container': string;
  'modal': string;
  'open': string;
  'subtitle': string;
  'title': string;
  'border': string;
}
export const cssExports: CssExports;
export default cssExports;
